name: 'Setup Node Dependencies'
description: 'Action to set up Node.js dependencies using pnpm'
runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: 'package.json'
        cache: 'pnpm'

    - name: Install Node.js dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
