name: 'Setup Node Dependencies'
description: 'Action to set up Node.js dependencies using pnpm'
runs:
  using: 'composite'
  steps:
    - name: Setup Runtime & Dependencies
      uses: pnpm/setup@v2
      with:
        # Installs Node.js based on the `packageManager` or `devEngines`
        # field inside your project's package.json
        # Automatically enables global pnpm store caching
        cache: true

        # Forces the automated setup to run `pnpm install --frozen-lockfile`
        frozen-lockfile: true
